import { expect, test, type Page } from "@playwright/test";

type MockPage = {
  id: string;
  title: string;
  parent_id: string | null;
  content: string | null;
  search_text: string | null;
  icon: string | null;
  cover_url: string | null;
  is_deleted: number;
  is_favorite: number;
  is_template: number;
  is_database: number;
  database_schema: string | null;
  properties: string | null;
  sort_order: number;
  page_kind: "note" | "studio_note";
  created_at: string;
  updated_at: string;
};

const storageKey = "opennotion-e2e-ai-pages";
const keyStorageKey = "opennotion-e2e-ai-key";
const conversationStorageKey = "opennotion-e2e-ai-conversations";
const messageStorageKey = "opennotion-e2e-ai-messages";
const lastRequestStorageKey = "opennotion-e2e-ai-last-request";

async function openAiFromCommandPalette(page: Page) {
  await page.keyboard.press("Meta+K");
  await expect(page.getByPlaceholder("Search pages...")).toBeFocused();
  await page.locator(".on-command-panel").getByText("Ask AI", { exact: true }).click();
  await expect(page.getByRole("button", { name: "Close AI" })).toBeVisible();
}

test.beforeEach(async ({ page }) => {
  await page.addInitScript(({ storageKey, keyStorageKey, conversationStorageKey, messageStorageKey, lastRequestStorageKey }) => {
    const loadPages = (): MockPage[] => JSON.parse(window.localStorage.getItem(storageKey) ?? "[]");
    const savePages = (pages: MockPage[]) => window.localStorage.setItem(storageKey, JSON.stringify(pages));
    const sortPages = (pages: MockPage[]) =>
      [...pages].filter((page) => page.is_deleted === 0).sort((first, second) => first.sort_order - second.sort_order);

    type MockConversation = { id: string; title: string; updated_at: string };
    type MockAiMessage = {
      id: string;
      role: "user" | "assistant";
      content: string;
      plan?: unknown;
      created_at: string;
    };
    const loadConversations = (): MockConversation[] => JSON.parse(window.localStorage.getItem(conversationStorageKey) ?? "[]");
    const saveConversations = (conversations: MockConversation[]) =>
      window.localStorage.setItem(conversationStorageKey, JSON.stringify(conversations));
    const loadMessages = (): Record<string, MockAiMessage[]> => JSON.parse(window.localStorage.getItem(messageStorageKey) ?? "{}");
    const saveMessages = (messages: Record<string, MockAiMessage[]>) =>
      window.localStorage.setItem(messageStorageKey, JSON.stringify(messages));

    let callbackCounter = 0;
    let cancelGenerationCount = 0;

    window.localStorage.removeItem(storageKey);
    window.localStorage.removeItem(keyStorageKey);
    window.localStorage.removeItem(conversationStorageKey);
    window.localStorage.removeItem(messageStorageKey);
    window.localStorage.removeItem(lastRequestStorageKey);
    window.localStorage.removeItem("opennotion-current-page-id");

    const aiSettings = () => ({
      provider: "openrouter",
      model: "moonshotai/kimi-k2.6:free",
      trusted_mode_enabled: false,
      has_api_key: window.localStorage.getItem(keyStorageKey) === "saved",
      api_key_source: window.localStorage.getItem(keyStorageKey) === "saved" ? "keychain" : null,
    });

    const studyPlan = (parentId: string | null) => ({
      version: 1,
      summary: "Create a study page.",
      requires_confirmation: true,
      actions: [
        {
          type: "create_page",
          title: "AI Study Plan",
          parent_id: parentId,
          content_blocks: [
            {
              type: "paragraph",
              content: [{ type: "text", text: "Generated by AI.", styles: {} }],
            },
          ],
        },
      ],
    });

    window.__TAURI_INTERNALS__ = {
      metadata: { currentWindow: { label: "main" } },
      transformCallback: () => {
        callbackCounter += 1;
        return callbackCounter;
      },
      unregisterCallback: () => undefined,
      convertFileSrc: (filePath: string) => filePath,
      invoke: async (cmd: string, args: Record<string, unknown> = {}) => {
        const pages = loadPages();

        if (cmd === "list_pages" || cmd === "list_all_pages") return sortPages(pages);

        if (cmd === "get_page") return pages.find((page) => page.id === args.id) ?? null;

        if (cmd === "create_page") {
          const page: MockPage = {
            id: args.id as string,
            title: (args.title as string) || "Untitled",
            parent_id: (args.parentId ?? args.parent_id ?? null) as string | null,
            content: null,
            search_text: null,
            icon: null,
            cover_url: null,
            is_deleted: 0,
            is_favorite: 0,
            is_template: 0,
            is_database: 0,
            database_schema: null,
            properties: null,
            sort_order: -1,
            page_kind: "note",
            created_at: args.createdAt as string,
            updated_at: args.createdAt as string,
          };
          savePages([page, ...pages]);
          return page;
        }

        if (cmd === "update_page") {
          const id = args.id as string;
          const updates = args.updates as Partial<MockPage>;
          savePages(pages.map((page) => page.id === id ? { ...page, ...updates, updated_at: args.updatedAt as string } : page));
          return null;
        }

        if (cmd === "search_pages") return [];
        if (cmd === "show_character_palette") return null;
        if (cmd === "cancel_ai_generation") {
          cancelGenerationCount += 1;
          return null;
        }

        if (cmd === "get_ai_settings") return aiSettings();

        if (cmd === "get_ai_models") {
          return [
            { id: "moonshotai/kimi-k2.6:free", label: "Kimi K2.6 Free", context_length: 131072 },
            { id: "deepseek/deepseek-v4-flash:free", label: "DeepSeek V4 Flash Free", context_length: 65536 },
          ];
        }

        if (cmd === "save_ai_api_key") {
          window.localStorage.setItem(keyStorageKey, "saved");
          return aiSettings();
        }

        if (cmd === "clear_ai_api_key") {
          window.localStorage.removeItem(keyStorageKey);
          return aiSettings();
        }

        if (cmd === "update_ai_settings") {
          return {
            ...(args.settings as Record<string, unknown>),
            has_api_key: window.localStorage.getItem(keyStorageKey) === "saved",
            api_key_source: window.localStorage.getItem(keyStorageKey) === "saved" ? "keychain" : null,
          };
        }

        if (cmd === "list_ai_conversations") {
          return [...loadConversations()].sort((first, second) => second.updated_at.localeCompare(first.updated_at));
        }

        if (cmd === "create_ai_conversation") {
          const createdAt = (args.createdAt as string) ?? new Date().toISOString();
          const conversation: MockConversation = {
            id: `conv-${loadConversations().length + 1}-${callbackCounter}`,
            title: "New chat",
            updated_at: createdAt,
          };
          saveConversations([conversation, ...loadConversations()]);
          const store = loadMessages();
          store[conversation.id] = [];
          saveMessages(store);
          return conversation;
        }

        if (cmd === "get_ai_conversation") {
          const id = args.id as string;
          const conversation = loadConversations().find((item) => item.id === id) ?? {
            id,
            title: "New chat",
            updated_at: new Date().toISOString(),
          };
          return { conversation, messages: loadMessages()[id] ?? [] };
        }

        if (cmd === "rename_ai_conversation") {
          const id = args.id as string;
          const title = args.title as string;
          const updatedAt = (args.updatedAt as string) ?? new Date().toISOString();
          saveConversations(loadConversations().map((item) => item.id === id ? { ...item, title, updated_at: updatedAt } : item));
          return null;
        }

        if (cmd === "delete_ai_conversation") {
          const id = args.id as string;
          saveConversations(loadConversations().filter((item) => item.id !== id));
          const store = loadMessages();
          delete store[id];
          saveMessages(store);
          return null;
        }

        if (cmd === "stream_ai_chat_reply") {
          const request = args.request as {
            conversation_id: string;
            prompt: string;
            current_page_id?: string | null;
            regenerate?: boolean;
          };
          const createdAt = (args.createdAt as string) ?? new Date().toISOString();
          window.localStorage.setItem(lastRequestStorageKey, JSON.stringify(request));

          const conversationId = request.conversation_id;
          const store = loadMessages();
          let nextMessages = store[conversationId] ? [...store[conversationId]] : [];
          if (request.regenerate) {
            if (nextMessages.length > 0 && nextMessages[nextMessages.length - 1].role === "assistant") {
              nextMessages = nextMessages.slice(0, -1);
            }
          } else {
            nextMessages.push({
              id: `msg-user-${nextMessages.length + 1}`,
              role: "user",
              content: request.prompt,
              created_at: createdAt,
            });
          }

          const assistant: MockAiMessage = {
            id: `msg-assistant-${nextMessages.length + 1}`,
            role: "assistant",
            content: "Here is a study plan.",
            plan: studyPlan(request.current_page_id ?? null),
            created_at: createdAt,
          };
          nextMessages.push(assistant);
          store[conversationId] = nextMessages;
          saveMessages(store);

          saveConversations(loadConversations().map((item) => item.id === conversationId
            ? { ...item, updated_at: createdAt, title: item.title === "New chat" ? request.prompt.slice(0, 40) : item.title }
            : item));

          return assistant;
        }

        if (cmd === "generate_ai_action_plan" || cmd === "generate_ai_action_plan_streaming") {
          return studyPlan((args.request as { current_page_id?: string | null }).current_page_id ?? null);
        }

        if (cmd === "apply_ai_action_plan") {
          const plan = args.plan as { actions: Array<{ type: string; title?: string; parent_id?: string | null; content_blocks?: unknown[] }> };
          // Mirror the backend: search_text is plain extracted text (not raw
          // block JSON) and the timestamp comes from the caller's createdAt.
          const searchTextFromBlocks = (blocks: unknown[] | undefined): string =>
            (Array.isArray(blocks) ? blocks : [])
              .map((block) => {
                const content = (block as { content?: unknown }).content;
                return Array.isArray(content)
                  ? content.map((item) => (typeof (item as { text?: unknown }).text === "string" ? (item as { text: string }).text : "")).join(" ")
                  : "";
              })
              .join(" ")
              .replace(/\s+/g, " ")
              .trim();
          const createdAt = (args.createdAt as string) ?? "2026-05-31T00:00:00.000Z";
          const created: string[] = [];
          const nextPages = [...pages];
          for (const action of plan.actions) {
            if (action.type !== "create_page") continue;
            const id = `ai-page-${created.length + 1}`;
            created.push(id);
            const searchText = searchTextFromBlocks(action.content_blocks);
            nextPages.unshift({
              id,
              title: action.title ?? "AI Page",
              parent_id: action.parent_id ?? null,
              content: JSON.stringify(action.content_blocks ?? []),
              search_text: searchText.length > 0 ? searchText : null,
              icon: null,
              cover_url: null,
              is_deleted: 0,
              is_favorite: 0,
              is_template: 0,
              is_database: 0,
              database_schema: null,
              properties: null,
              sort_order: -10 - created.length,
              page_kind: "note",
              created_at: createdAt,
              updated_at: createdAt,
            });
          }
          savePages(nextPages);
          return { created_page_ids: created, updated_page_ids: [], primary_page_id: created[0] ?? null };
        }

        throw new Error(`Unhandled e2e command: ${cmd}`);
      },
    };
  }, { storageKey, keyStorageKey, conversationStorageKey, messageStorageKey, lastRequestStorageKey });
});

test("opens AI from command palette and explains missing API key", async ({ page }) => {
  await page.goto("/");
  await openAiFromCommandPalette(page);

  const panel = page.locator(".on-ai-chat-modal");
  const panelBox = await panel.boundingBox();
  const viewport = page.viewportSize();
  expect(panelBox).not.toBeNull();
  expect(viewport).not.toBeNull();
  expect(panelBox!.x).toBeGreaterThan(viewport!.width - panelBox!.width - 24);
  await expect(page.locator(".on-ai-chat-backdrop")).toHaveCSS("background-color", "rgba(0, 0, 0, 0)");
  await expect(page.getByText("Needs key")).toBeVisible();
  await page.getByRole("textbox", { name: "Message AI" }).fill("Create an exam tracker");
  await expect(page.getByLabel("Send")).toBeDisabled();
});

test("side panel controls update composer state and request options", async ({ page }) => {
  await page.goto("/");
  await page.evaluate((key) => window.localStorage.setItem(key, "saved"), keyStorageKey);

  await openAiFromCommandPalette(page);
  const panel = page.locator(".on-ai-chat-modal");
  const compactWidth = (await panel.boundingBox())!.width;
  await page.getByLabel("Toggle panel").click();
  await expect(page.getByLabel("Toggle panel")).toHaveAttribute("aria-pressed", "true");
  expect((await panel.boundingBox())!.width).toBeGreaterThan(compactWidth);

  await page.getByLabel("More AI actions").click();
  await page.getByRole("menuitem", { name: "Open settings" }).click();
  await expect(page.getByRole("menu", { name: "AI settings" })).toBeVisible();

  const webToggle = page.getByRole("button", { name: "Toggle web access" });
  await expect(webToggle).toHaveAttribute("aria-pressed", "true");
  await webToggle.click();
  await expect(webToggle).toHaveAttribute("aria-pressed", "false");
  await page.getByRole("button", { name: /Plan/ }).click();
  await expect(page.locator(".on-ai-auto-label")).toHaveText("Plan");
  await page.getByRole("button", { name: "Personalize" }).click();
  await expect(page.getByRole("dialog", { name: "Personalize AI" })).toBeVisible();
  await page.getByLabel("AI name").fill("Workspace Helper");
  await page.getByLabel("Next AI icon").click();
  await page.getByRole("button", { name: "Add instructions" }).click();
  await page.getByRole("button", { name: "Done" }).click();
  await expect(page.getByRole("dialog", { name: "Personalize AI" })).toBeHidden();

  await page.getByLabel("Add sources").click();
  await page.getByRole("menuitem", { name: "Mention pages or people" }).click();
  await expect(page.getByRole("textbox", { name: "Message AI" })).toHaveValue(/@New page/);
  await page.locator(".on-ai-hidden-file-input").setInputFiles({
    name: "requirements.csv",
    mimeType: "text/csv",
    buffer: Buffer.from("title,status\nTask,Todo\n"),
  });
  await expect(page.getByLabel("Attached sources")).toContainText("requirements.csv");

  await page.getByRole("textbox", { name: "Message AI" }).fill("Create a task tracker");
  await page.getByLabel("Send").click();
  await expect(page.locator(".on-ai-markdown").getByText("Here is a study plan.")).toBeVisible();

  const lastRequest = await page.evaluate((key) => JSON.parse(window.localStorage.getItem(key) ?? "{}"), lastRequestStorageKey);
  expect(lastRequest.prompt).toBe("Create a task tracker");
  expect(lastRequest.mode).toBe("plan");
  expect(lastRequest.web_access_enabled).toBe(false);
  expect(lastRequest.persona_name).toBe("Workspace Helper");
  expect(lastRequest.persona_instructions_added).toBe(true);
  expect(lastRequest.attached_sources).toEqual(["requirements.csv"]);
  await expect(page.locator(".on-ai-user-pill")).toHaveText("Create a task tracker");
});

test("generates an AI create-only preview and applies it", async ({ page }) => {
  await page.goto("/");
  await page.evaluate((key) => window.localStorage.setItem(key, "saved"), keyStorageKey);

  await openAiFromCommandPalette(page);
  await page.getByRole("textbox", { name: "Message AI" }).fill("Create a study page for this topic");
  await page.getByLabel("Send").click();

  await expect(page.locator(".on-ai-markdown").getByText("Here is a study plan.")).toBeVisible();
  await expect(page.locator(".on-ai-action-card").getByText("Create a study page.")).toBeVisible();
  await expect(page.locator(".on-ai-action-card").getByText("Create page: AI Study Plan")).toBeVisible();
  await page.getByRole("button", { name: /Apply \d+ selected/i }).click();

  await expect(page.locator("textarea[placeholder='Untitled']")).toHaveValue("AI Study Plan");
  await expect(page.getByText(/AI applied 1 item/i)).toBeVisible();
});
